export const user = {
    email: 'm.orynbay@srgdev.kz',
    password: 'Qwerty123!!',
    passwordtest:'Qwerty123!!!',
    incorrectemail: 'm.orynbay@srgdev.kz1',
    incorrectpassword: 'errorpassword',
    testemail: 'xwkogypfnfztqalfyz@bvhrk.com',
    testCamera: 'Тест Сетка',
    noValueemail: '',
    noValuepass: '',
    deletedemail: 'cijpqxmmb@firste.ml',
    deletedpassword: '@O304!1uboea7P5H',
    blockedemail: 'vatiter217@peykesabz.com',
    blockedpassword: 'C!Yng1&t37J89uj4',
    remoteemail: 'hassletest917@gmail.com',
    remotepassword: 'E&5c[B90XY2r7i3S',
    notreguseremail: 'pakoj67899@showbaz.com',
    notreguserpass: 'E&5c[B90XY2r7i3S',
    cyrillicemail: 'фывфывукц',
    latinemail: 'aderfggkaskd',
    specsymbolemail:'!@#$%^&*()_+””№%:?*',
    symbolemail: 'alibaevwebgmail.com',
    emailnotdomain: 'm.orynbay@srgdev',
    emailnumber: '1234567890',
    adminemail: 'vms-admin@srgdev.kz',
    adminpassword: '1q2w3e',
    passwordcyrillic: 'фывфывфывфывфыв',
    passwordlatin: 'asdasdasdasdgds',
    passwordspecsymbol:'!@#$%^&*()_+”№%:',
    roles: ['Архив', 'ГИС', 'Журнал событий','Камеры', 'Лог действий','Организации','Отчеты','Пользователи','Роли','Серверы'],

};